---
title: "Precificação de Imóveis"
author: "Saulo Morellato"
format:
  dashboard:
    theme: sandstone
server: shiny
---


```{r}
#| context: setup

## PACOTES ##

library(tidyverse)  # manipulacao dos dados
library(plotly)     # graficos iterativos


## CARREGANDO OS DADOS ##

dados <- read.table("imoveis.txt", header=TRUE) %>% 
  data.frame()
```



# Dados

```{r}
tableOutput("tabela")
```



# Gráficos

## {.sidebar}

```{r}
selectInput("x",                                    # nome da variavel
            "Selecione uma variável",               # inscricao sobre o seletor
            names(dados)[-5]                        # lista de nomes
)
```

```{r}
#| context: server

#dataset <- reactive({
#  comandos para customizar os dados
#})

output$diag_dispersao <- renderPlot({
  
  #dataset() %>% ggplot() se os dados fossem manipulados
  
  p <- dados %>% ggplot(aes_string(x=input$x)) + 
    geom_point(aes(y=preco), size=2) + 
    ylab("Preço do Imóvel") +
    theme_bw()
  
  if(input$x=="imposto"){p<-p+xlab("Imposto pago pelo imóvel")}
  if(input$x=="areat"){p<-p+xlab("Área do terreno")}
  if(input$x=="areac"){p<-p+xlab("Área construída")}
  if(input$x=="idade"){p<-p+xlab("Idade do imóvel")}
  
  #ggplotly(p)
  p

})



output$tabela<- renderTable({
  dados
},align="c")


```


## Column

```{r}
#plotlyOutput("diag_dispersao")
plotOutput("diag_dispersao")
```




# Predição

